env:
    - TZ="Australia/Hobart"

before_script:
    - export MAVEN_OPTS="-Xmx2G -XX:MaxPermSize=512m"

before_install:
    - sudo apt-get install tzdata
    - sudo dpkg-reconfigure tzdata
    - sudo apt-get update
    - sudo apt-get install grails-1.3.7
    
language: groovy

jdk:
    - openjdk7

notifications:
  email: false
  