language: groovy

jdk:
    - openjdk7

env:
    global
    - TZ="Australia/Hobart" JAVA_OPTS="-Xmx1G -Xms512m -XX:PermSize=64m -XX:MaxPermSize=512m"

before_install:
    - sudo apt-get install tzdata
    - sudo dpkg-reconfigure tzdata

notifications:
  email:
    - jkburges@utas.edu.au
    - dnahodil@utas.edu.au
    - fotakt@utas.edu.au
